### ISSUE TITLE
Config Option to Disable the Custom Moon Cycle

### ISSUE THREAD

**Issue by LenKagamine** [Povstalec/StellarView#101]
Would it be possible to add a config option that turns off the custom moon behavior that makes it not tied to the position of the sun? Even with Static Sky turned on (which seems to be bugged with shaders, anyways), the moon still follows its own pattern. So when shaders are enabled the shadows cast by the moon are at a different angle than the moon itself is, because the moon isn't following vanilla behavior. Thanks for the mod!

**Comment by Noobly-Walker** [comment]
You can use a resource pack to modify the moon, to remove the moon phases and alter the texture.

**Comment by LenKagamine** [comment]
I'm not sure I understand. You can use a resource pack to disable the moon being in a different position in the sky each night?

**Comment by LenKagamine** [comment]
Yes, sorry for the misunderstanding.

**Comment by LenKagamine** [comment]
yes, exactly

**Comment by Noobly-Walker** [comment]
In the mod configuration (press G, usually), you can go to Overworld settings and enable Vanilla Moon. I think that should fix it, though be sure to make it give priority to the config over resources.

**Comment by Archer3695** [comment]
> In the mod configuration (press G, usually), you can go to Overworld settings and enable Vanilla Moon. I think that should fix it, though be sure to make it give priority to the config over resources.

I'm not entirely sure if this works on the latest version. I set Vanilla Moon to "True", enabled "Prioritize Config", and the moon will still appear out of place, such as when I use "/time set midnight" after some in-game days has past, when it should be directly on above the player.

**Comment by Apollonu** [comment]
Im also having trouble with this, I can only have the moon be in the places the vanilla moon would be by disabling replace vanilla in the overworld (which disables the skybox.) The Vanilla Moon setting simply makes the moon always be a png of a full moon and does not correct its placement. It would be nice just for the moon cycle to have a config, the reason why I want this is because with Better Clouds, the illumination of the clouds is not synced with this moon, also with shaders for compatibility.

**Comment by musicbynumbers** [comment]
I have this issue too, Maybe it's down to having mods that modify the seasons and day/night ratio like serene seasons plus with better days mod. Maybe this are breaking the moon position?

I tried to use game ticks and other settings but i can't get the moon to align. This breaks shaders in the case that the moonlight is coming from the wrong place in the sky.

Hope there's a way to fix this as love your mod! :)
